### ISSUE TITLE
open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory

### ISSUE THREAD

**Issue by bay1** [TruthHun/DocHub#11]
具体的报错信息如下：
```
2018-07-19 17:28:32:[ORM]2018/07/19 09:28:32 register db Ping `default`, open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory
2018-07-19 17:28:32:panic: register db Ping `default`, open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory
2018-07-19 17:28:32:goroutine 1 [running]:
2018-07-19 17:28:32:github.com/TruthHun/DocHub/models.RegisterDB()
2018-07-19 17:28:32:	/Users/TruthHun/goworkspace/src/github.com/TruthHun/DocHub/models/Models.go:203 +0xb00
2018-07-19 17:28:32:github.com/TruthHun/DocHub/models.Init()
2018-07-19 17:28:32:	/Users/TruthHun/goworkspace/src/github.com/TruthHun/DocHub/models/Models.go:119 +0x26
2018-07-19 17:28:32:main.init.0()
2018-07-19 17:28:32:	/Users/TruthHun/goworkspace/src/github.com/TruthHun/DocHub/main.go:24 +0x180
2018-07-19 17:28:32:main.init()
2018-07-19 17:28:32:	<autogenerated>:1 +0x6c
```

显示是zoneinfo处理的问题
参考下面的链接，我修改我的docker-compose
可以解决

```
version: '2'
services:
  dochub:
    build: .
    volumes:
    - /home/flyingstudio/wenku/conf:/www/dochub/conf
    - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    ports:
      - 8090:8090
    restart: always
```

[FATAL: Invalid OffPeakPeriods value: open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory.](https://gitlab.com/gitlab-org/gitlab-runner/issues/3244)

PS:在其他地方也看到了一些解决办法，您可以参考下：
[pod error: panic: open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory](https://github.com/asobti/kube-monkey/issues/7)

**Comment by bay1** [comment]
#13
